### PR TITLE
Create Kamlesh_Joshi.md

### PR DESCRIPTION
**Pull request by kamleshjoshi8102**

### CODE REVIEW

**Comment by xlogix** [comment]
Welcome to the community!

**Comment by kamleshjoshi8102** [comment]
> Welcome to the community!

Thank you! 
How can I join Organisation?

**Comment by kamleshjoshi8102** [comment]
> > Welcome to the community!
> 
> Thank you!
> How can I join Organisation?

@xlogix?

**Comment by xlogix** [comment]
Oh sorry didn't see that. You can go to https://fnplus-inviter.herokuapp.com/ and just add your Github username and email.

**Comment by kamleshjoshi8102** [comment]
> Oh sorry didn't see that. You can go to https://fnplus-inviter.herokuapp.com/ and just add your Github username and email.

Thank You sir I added but no response :)

**Pull request merged**
