### PR TITLE
Added Kushal Das.md file

### PR DESCRIPTION
**Pull request by Kushal997-das**

### CODE REVIEW

**Comment by xlogix** [comment]
Welcome, Kushal! Happy to see you here.

**Comment by Kushal997-das** [comment]
> Welcome, Kushal! Happy to see you here.

I want to join this organization . How to join it ?

**Comment by xlogix** [comment]
Can you check if you got it?

**Comment by Kushal997-das** [comment]
> Can you check if you got it?

Yes I got it. 
Thanks :)

**Pull request merged**
