### PR TITLE
Added gargk747.md in Members

### PR DESCRIPTION
**Pull request by gargk747**
Please review and approve it.

### CODE REVIEW

**Comment by xlogix** [comment]
Welcome to the community!

**Review by Kushal997-das — COMMENTED** [review]
great:)

**Comment by gargk747** [comment]
> Welcome to the community!

Hey @xlogix I didn't got the joining request yet. Is there something error?

**Comment by xlogix** [comment]
Hey Keshav, you should have it now! Let me know

**Comment by xlogix** [comment]
We can probably work on automating the process of sending the invites on a successful merge to this repo...

**Pull request merged**
