### PR TITLE
Adding self as a contributor. 

### PR DESCRIPTION
**Pull request by hqrshguptq**
Hey concerned contributors.
Do check this :). Happy Hacking, ATB!

### CODE REVIEW

**Comment by xlogix** [comment]
Welcome to the community Harsh! 😄

**Comment by hqrshguptq** [comment]
Yea, Could you just put up some tasks which are yet to be completed marking my skills..?

**Comment by xlogix** [comment]
Maybe you could help out with footsteps-app? Wanna convert it to a next.js app!

**Comment by xlogix** [comment]
There are other features on the roadmap and issues which you can work on!

**Comment by hqrshguptq** [comment]
Cool, Will look over it. :)

**Pull request merged**
